### PR TITLE
[lineage-18.0] Initial device bringup

### PR DESCRIPTION
**Pull request by derfelot**
DNM yet, still working on a few quirks

### CODE REVIEW

**Comment by derfelot** [comment]
That's odd

for maple, are you using this?

https://review.lineageos.org/c/LineageOS/android_device_htc_msm8974-common/+/291301

That's the main thing that comes to mind that maple needs and poplar/lilac don't

**Comment by ShujathMohd** [comment]
> Hey I have device maple,
> Been trying to boot it up for a pretty long time...
> I saw that some libs need to be patched to be compatible with Android 11
> 
> Here is a Console ramoops log
> 
> CANNOT LINK EXECUTABLE "/system/bin/init": cannot locate symbol "_ZN3fmt2v68internal10basic_dataIvE23zero_or_powers_of_10_32E" referenced by "/system/bin/init"...
> [ 2.380733] linker: CANNOT LINK EXECUTABLE "/system/bin/init": cannot locate symbol "_ZN3fmt2v68internal10basic_dataIvE23zero_or_powers_of_10_32E" referenced by "/system/bin/init"...
> [ 2.380733]
> 
> For full log:
> https://del.dog/eketipyrfa.txt
> 
> Ur help will be very useful for us

Wait for derfelot to do initial release of LOS 18.0
It will be released for maple too , I am waiting for the work to be completed on the trees so that it can be rebased/adapted for maple.
Thats why you dont see any A11 trees for maple now :)

**Comment by ShujathMohd** [comment]
@derfelot Do you think we still need VR from Cheeseburget?
When you did the bringup Los was not tracking the vr hal and its enabled now.

https://github.com/LineageOS/android/commit/2566eb412f845a7bb68bb951c70fb93adcf18556

**Comment by derfelot** [comment]
> @derfelot Do you think we still need VR from Cheeseburget?
> When you did the bringup Los was not tracking the vr hal and its enabled now.
> 
> [LineageOS/android@2566eb4](https://github.com/LineageOS/android/commit/2566eb412f845a7bb68bb951c70fb93adcf18556)

in that case probably not. will try reverting those and see if it gets built again. thanks for heads up :)

**Pull request merged**
